# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mainUI.ui'
#
# Created: Thu Aug 27 16:24:51 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_guiDlg(object):
    def setupUi(self, guiDlg):
        guiDlg.setObjectName("guiDlg")
        guiDlg.resize(1140, 918)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(guiDlg.sizePolicy().hasHeightForWidth())
        guiDlg.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtGui.QGridLayout(guiDlg)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(guiDlg)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.zoom = QtGui.QSpinBox(guiDlg)
        self.zoom.setMinimum(1)
        self.zoom.setProperty("value", 10)
        self.zoom.setObjectName("zoom")
        self.verticalLayout.addWidget(self.zoom)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.captureButton = QtGui.QPushButton(guiDlg)
        self.captureButton.setObjectName("captureButton")
        self.verticalLayout.addWidget(self.captureButton)
        self.name = QtGui.QLineEdit(guiDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name.sizePolicy().hasHeightForWidth())
        self.name.setSizePolicy(sizePolicy)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_6 = QtGui.QLabel(guiDlg)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.activationBox = QtGui.QComboBox(guiDlg)
        self.activationBox.setObjectName("activationBox")
        self.verticalLayout.addWidget(self.activationBox)
        self.colorBox = QtGui.QComboBox(guiDlg)
        self.colorBox.setObjectName("colorBox")
        self.colorBox.addItem("")
        self.colorBox.addItem("")
        self.colorBox.addItem("")
        self.colorBox.addItem("")
        self.verticalLayout.addWidget(self.colorBox)
        self.showCurrent = QtGui.QCheckBox(guiDlg)
        self.showCurrent.setChecked(True)
        self.showCurrent.setObjectName("showCurrent")
        self.verticalLayout.addWidget(self.showCurrent)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_5 = QtGui.QLabel(guiDlg)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.controlBox = QtGui.QComboBox(guiDlg)
        self.controlBox.setObjectName("controlBox")
        self.verticalLayout.addWidget(self.controlBox)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.x = QtGui.QDoubleSpinBox(guiDlg)
        self.x.setDecimals(0)
        self.x.setMinimum(-10000.0)
        self.x.setMaximum(10000.0)
        self.x.setObjectName("x")
        self.gridLayout.addWidget(self.x, 1, 0, 1, 1)
        self.alpha = QtGui.QDoubleSpinBox(guiDlg)
        self.alpha.setDecimals(3)
        self.alpha.setMinimum(-7.0)
        self.alpha.setMaximum(7.0)
        self.alpha.setObjectName("alpha")
        self.gridLayout.addWidget(self.alpha, 1, 2, 1, 1)
        self.z = QtGui.QDoubleSpinBox(guiDlg)
        self.z.setDecimals(0)
        self.z.setMinimum(-10000.0)
        self.z.setObjectName("z")
        self.gridLayout.addWidget(self.z, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(guiDlg)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(guiDlg)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(guiDlg)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveButton = QtGui.QPushButton(guiDlg)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_3.addWidget(self.saveButton)
        self.loadButton = QtGui.QPushButton(guiDlg)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_3.addWidget(self.loadButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.graphicsViewLaser = QtGui.QGraphicsView(guiDlg)
        self.graphicsViewLaser.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(22)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewLaser.sizePolicy().hasHeightForWidth())
        self.graphicsViewLaser.setSizePolicy(sizePolicy)
        self.graphicsViewLaser.setMinimumSize(QtCore.QSize(900, 900))
        self.graphicsViewLaser.setMaximumSize(QtCore.QSize(90000, 90000))
        self.graphicsViewLaser.setProperty("cursor", QtCore.Qt.ArrowCursor)
        self.graphicsViewLaser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.graphicsViewLaser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.graphicsViewLaser.setInteractive(True)
        self.graphicsViewLaser.setObjectName("graphicsViewLaser")
        self.gridLayout_2.addWidget(self.graphicsViewLaser, 0, 1, 1, 1)

        self.retranslateUi(guiDlg)
        QtCore.QMetaObject.connectSlotsByName(guiDlg)

    def retranslateUi(self, guiDlg):
        guiDlg.setWindowTitle(QtGui.QApplication.translate("guiDlg", "Map Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("guiDlg", "zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.captureButton.setText(QtGui.QApplication.translate("guiDlg", "capture", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("guiDlg", "Activation", None, QtGui.QApplication.UnicodeUTF8))
        self.colorBox.setItemText(0, QtGui.QApplication.translate("guiDlg", "not displayed", None, QtGui.QApplication.UnicodeUTF8))
        self.colorBox.setItemText(1, QtGui.QApplication.translate("guiDlg", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.colorBox.setItemText(2, QtGui.QApplication.translate("guiDlg", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.colorBox.setItemText(3, QtGui.QApplication.translate("guiDlg", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.showCurrent.setText(QtGui.QApplication.translate("guiDlg", "show current ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("guiDlg", "Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("guiDlg", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("guiDlg", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("guiDlg", "alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("guiDlg", "save", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setText(QtGui.QApplication.translate("guiDlg", "load", None, QtGui.QApplication.UnicodeUTF8))

